# Generated by Django 3.0.2 on 2020-02-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerolinea', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('precio', models.IntegerField(default=100)),
                ('descuento', models.IntegerField(default=85)),
            ],
        ),
    ]
